In [1]:
import numpy as np
import pandas as pd

# Proteomics

In [25]:
protein = pd.read_csv('./protein_abundances_JL.tsv', sep='\t')
protein.head()

,Symbol,28iALS_1,28iALS_2,29iALS_1,29iALS_2,30iALS_1,52iALS_1,52iALS_2,00iCTR_1,00iCTR_2,25iCTR_1_A,25iCTR_1_B,25iCTR_2,83iCTR_1,83iCTR_2
0,UBA6,1515.96,1325.49,2046.09,2373.03,3139.98,1888.97,1133.23,2428.80,2369.05,3298.28,3562.29,4558.27,2698.67,2410.73
1,ESYT2,0.00,0.00,166.46,245.38,140.69,0.00,0.00,0.00,0.00,88.14,81.26,0.00,92.94,24.49
2,SHTN1,0.00,0.00,0.00,64.01,206.67,0.00,179.03,93.06,70.56,329.18,274.13,758.07,1469.21,1535.94
3,GXYLT2,45.16,0.00,220.66,135.43,0.00,556.94,390.97,40.96,37.02,22.63,0.00,0.00,0.00,25.72
4,ILVBL,0.00,200.78,670.33,765.68,493.34,426.52,122.09,355.28,155.03,690.57,623.43,1104.38,645.16,752.21

In [34]:
protein[protein.duplicated('Symbol', keep=False)]

,Symbol,28iALS_1,28iALS_2,29iALS_1,29iALS_2,30iALS_1,52iALS_1,52iALS_2,00iCTR_1,00iCTR_2,25iCTR_1_A,25iCTR_1_B,25iCTR_2,83iCTR_1,83iCTR_2
1142,TMPO,97.56,277.71,421.52,516.68,622.26,915.61,492.38,821.63,743.06,796.69,604.21,646.67,616.47,514.38
1143,TMPO,11056.10,15455.20,19644.70,18770.50,12320.40,22956.80,13455.50,38782.20,31021.30,27139.30,27785.90,26149.80,21507.10,13254.50

In [41]:
protein = protein.drop(protein.index[[1142]])
protein.loc[1141:1144]

,Symbol,28iALS_1,28iALS_2,29iALS_1,29iALS_2,30iALS_1,52iALS_1,52iALS_2,00iCTR_1,00iCTR_2,25iCTR_1_A,25iCTR_1_B,25iCTR_2,83iCTR_1,83iCTR_2
1141,ECI1,417.55,1708.57,4864.76,4880.71,3327.45,2309.01,700.29,3516.64,2464.87,5150.95,5255.14,5286.32,3024.46,3124.55
1143,TMPO,11056.10,15455.20,19644.70,18770.50,12320.40,22956.80,13455.50,38782.20,31021.30,27139.30,27785.90,26149.80,21507.10,13254.50
1144,STAT1,511.31,700.82,2181.72,2205.62,3070.15,1426.33,666.01,800.58,479.76,3673.22,3546.43,4603.48,1832.12,1887.76

In [43]:
protein = protein.set_index('Symbol')
protein.head()

,28iALS_1,28iALS_2,29iALS_1,29iALS_2,30iALS_1,52iALS_1,52iALS_2,00iCTR_1,00iCTR_2,25iCTR_1_A,25iCTR_1_B,25iCTR_2,83iCTR_1,83iCTR_2
Symbol,,,,,,,,,,,,,,
UBA6,1515.96,1325.49,2046.09,2373.03,3139.98,1888.97,1133.23,2428.80,2369.05,3298.28,3562.29,4558.27,2698.67,2410.73
ESYT2,0.00,0.00,166.46,245.38,140.69,0.00,0.00,0.00,0.00,88.14,81.26,0.00,92.94,24.49
SHTN1,0.00,0.00,0.00,64.01,206.67,0.00,179.03,93.06,70.56,329.18,274.13,758.07,1469.21,1535.94
GXYLT2,45.16,0.00,220.66,135.43,0.00,556.94,390.97,40.96,37.02,22.63,0.00,0.00,0.00,25.72
ILVBL,0.00,200.78,670.33,765.68,493.34,426.52,122.09,355.28,155.03,690.57,623.43,1104.38,645.16,752.21

In [44]:
protein.to_json('protein.json')

# Transcriptomics

In [46]:
transcripts = pd.read_csv('./rna_abundances_JL.tsv', sep='\t')
transcripts.head()

,symbol,00iCTR_1,25iCTR_1,83iCTR_1,28iALS_1,29iALS_1,30iALS_1,52iALS_1,00iCTR_2,25iCTR_2,83iCTR_2,28iALS_2,29iALS_2,30iALS_2,52iALS_2
0,TSPAN6,15.07520,42.212200,31.045900,23.438800,18.67430,23.518300,15.95140,18.99350,50.810600,37.202600,19.376000,19.72610,24.37710,16.93510
1,TNMD,3.46409,0.180462,0.209293,0.379753,1.38633,0.097987,7.19405,5.31750,0.152618,0.322817,0.603215,1.69970,0.12456,7.99093
2,DPM1,14.45850,15.473800,16.354500,12.372100,24.01650,17.426000,22.02340,18.79230,15.512700,17.521900,11.414600,24.04870,15.75790,20.58920
3,SCYL3,3.62369,2.468500,2.895030,3.202920,2.35784,2.196690,2.45420,3.91679,3.179870,2.835270,2.731020,2.44931,2.30431,2.35572
4,C1orf112,4.55001,2.773590,2.880550,1.738930,2.35351,4.300850,2.57059,6.02910,2.752660,3.493480,1.977490,2.68149,4.26484,3.07295

In [48]:
transcripts[transcripts.duplicated('symbol', keep=False)]

,symbol,00iCTR_1,25iCTR_1,83iCTR_1,28iALS_1,29iALS_1,30iALS_1,52iALS_1,00iCTR_2,25iCTR_2,83iCTR_2,28iALS_2,29iALS_2,30iALS_2,52iALS_2
119,KRT33A,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
137,AGK,6.652920,6.782470,6.705490,8.498440,7.175460,7.463480,6.283780,8.401210,7.826070,7.477400,8.242860,7.731610,6.803810,6.301910
728,SYNE2,12.543700,9.219550,20.321400,14.236600,6.345310,9.832820,6.655190,11.611200,10.974100,20.879800,13.194900,5.272600,10.188500,7.366990
729,SYNE2,0.125712,0.000000,0.055844,0.075691,0.000000,0.122600,0.000000,0.000000,0.000000,0.060200,0.057673,0.051430,0.140259,0.050605
762,KIFC1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
835,CDH3,0.062083,0.107110,0.055234,0.073313,0.102287,0.057206,0.000000,0.057683,0.086164,0.000000,0.112172,0.142941,0.086770,0.000000
836,CDH3,1.898660,1.537070,2.943540,3.186920,4.930680,3.310170,3.410860,2.089190,1.508150,2.448410,2.681300,4.907780,3.468020,3.070170
970,ZNRD1,9.723120,8.069770,9.221410,7.678770,10.092100,9.160190,10.551000,12.398200,10.866900,11.385100,6.946990,9.904930,8.114340,12.081600
1046,ATP11A,4.908960,2.765230,3.984570,3.117400,2.584590,2.810190,3.331990,4.270140,3.466180,3.987330,2.569060,2.520620,2.787430,3.948490
1047,ATP11A,0.101993,0.000000,0.000000,0.000000,0.000000,0.000000,0.103436,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.234438
1064,TRPC7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.116451,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1065,TRPC7,0.032459,0.033272,0.012291,0.200184,0.036238,0.061371,0.041731,0.034222,0.014873,0.059275,0.107648,0.016930,0.023292,0.043626
1084,NaN,2.990400,1.355960,1.458130,4.882330,1.044500,1.523960,0.281826,3.584750,1.748130,1.495010,4.335790,1.090530,1.465790,0.286229
1327,ARHGAP15,0.020166,0.017671,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1328,ARHGAP15,0.362245,0.423100,0.182651,0.081408,0.212910,0.066608,0.118050,0.250713,0.457866,0.000000,0.145676,0.060937,0.454969,0.000000
1405,PIAS2,11.226800,10.592500,14.843800,12.729200,11.333300,15.851100,10.812000,12.017500,12.996000,16.675700,11.030200,10.464900,15.264800,10.354500
1406,PIAS2,0.000000,0.000000,0.000000,0.322757,0.000000,0.127849,0.425158,0.122788,0.180404,0.244885,0.000000,0.000000,0.000000,0.107545
1533,PTPRC,0.014067,0.128322,0.003968,0.000000,0.000000,0.076410,0.018795,0.012559,0.000000,0.000000,0.038104,0.019062,0.006758,0.040547
2005,KRT31,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2059,RPS18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2060,BAG6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2061,VARS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2216,LOC107987479,3.097480,0.456625,1.269460,1.559210,0.676233,0.755547,0.320251,2.380810,0.510730,1.382490,2.027270,0.630700,0.661878,0.562306
2219,TCF20,10.139300,9.221260,12.452500,14.382100,8.418160,8.603980,7.529760,12.394600,11.101500,15.079700,13.132000,8.450020,8.497310,7.192740
2397,CINP,4.803070,7.389160,7.323780,7.384560,7.943470,7.372200,8.267460,6.299900,8.745140,7.069740,6.102970,7.289180,7.849060,8.230770
2398,CINP,0.652972,1.739550,0.983184,0.666932,0.310878,0.713679,0.668177,1.130380,1.603770,1.244030,1.211190,1.050480,0.897674,1.305490
2552,VAPA,0.734363,0.704307,0.444551,0.000000,0.402690,0.630615,0.335600,0.596597,0.682728,0.312402,0.393388,0.250607,0.706041,0.389675
2553,VAPA,36.789000,49.890600,42.239400,61.437700,44.382000,43.773300,43.233400,44.701000,58.162400,47.263400,47.411800,43.481100,42.784500,46.592400
2986,ARHGEF18,7.079260,10.119900,13.410000,8.827900,10.292600,10.318800,7.304550,7.939680,11.467200,11.400400,9.087120,8.611840,9.856950,7.000420
3244,SSBP1,34.844900,46.512400,46.343800,38.144500,54.346000,52.292800,56.219900,48.330100,54.219300,51.903700,38.980300,53.084200,51.763300,54.558400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37483,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37492,NOP56P1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37494,RPL13P,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37497,DOC2B,4.469980,0.336196,1.329400,8.712160,1.184840,0.341010,1.146440,5.198940,0.469261,1.481310,9.544220,0.993435,0.391523,1.115430
37501,DOC2B,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37510,TAS2R8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37511,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37516,NDUFA6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37519,PRH2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37521,TAS2R10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37522,OLA1P1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37524,SMDT1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37526,NaN,0.888718,2.092340,1.309340,1.027670,1.621150,1.846520,2.321590,0.543720,0.540656,0.922034,1.362600,2.946540,1.050890,1.015240
37527,DDX11L8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37534,SMDT1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37536,NDST2,0.924953,0.770117,0.488100,0.783767,0.455292,0.841890,0.471919,1.185510,0.505403,0.993444,1.128840,0.741749,0.671813,0.439844
37555,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37559,NOP56P1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37560,TAS2R9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37561,TAS2R20,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37563,RPL13P,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37567,TAS2R15P,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37572,OLA1P1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37582,RPL13P,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37589,NOP56P1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37590,TAS2R7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37596,MICE,0.000000,0.000000,0.000000,0.000000,0.005183,0.000000,0.031022,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37601,NDUFA6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37604,TAS2R50,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
37607,TAS2R13,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [57]:
transcripts = transcripts.groupby('symbol').sum(axis=1)

In [75]:
transcripts = transcripts.reset_index().dropna(axis=0, subset=['symbol']).set_index('symbol')

In [81]:
transcripts = transcripts[transcripts.sum(axis=1) != 0]

In [82]:
transcripts.to_json('transcripts.json')

# Metadata

In [87]:
set(transcripts.columns)

{'00iCTR_1',
 '00iCTR_2',
 '25iCTR_1',
 '25iCTR_2',
 '28iALS_1',
 '28iALS_2',
 '29iALS_1',
 '29iALS_2',
 '30iALS_1',
 '30iALS_2',
 '52iALS_1',
 '52iALS_2',
 '83iCTR_1',
 '83iCTR_2'}

In [88]:
set(protein.columns)

{'00iCTR_1',
 '00iCTR_2',
 '25iCTR_1_A',
 '25iCTR_1_B',
 '25iCTR_2',
 '28iALS_1',
 '28iALS_2',
 '29iALS_1',
 '29iALS_2',
 '30iALS_1',
 '52iALS_1',
 '52iALS_2',
 '83iCTR_1',
 '83iCTR_2'}

In [89]:
set(transcripts.columns) - set(protein.columns)

{'25iCTR_1', '30iALS_2'}

In [90]:
set(protein.columns) - set(transcripts.columns)

{'25iCTR_1_A', '25iCTR_1_B'}